import {StyleSheet} from 'react-native';
import colors from '../../services/colors';
import {mvs, width} from '../../services/metrices';

export const Styles = StyleSheet.create({
  conntainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  body: {
    flex: 1,
    // paddingVertical: mvs(20),
  },
  card: {
    // backgroundColor: colors.white,
    borderRadius: mvs(20),
    marginBottom: mvs(20),
    ...colors.shadow,
  },
  image: {
    height: mvs(200),
    width: '100%',
  },
  ratingBar: {
    height: mvs(6),
    borderRadius: mvs(5),
    backgroundColor: colors.ratingLine,
    width: '100%',
    marginTop: mvs(5.5),
  },
  ratingPercentage: {
    height: mvs(6),
    borderRadius: mvs(5),
    backgroundColor: colors.primary,
  },
  warningMainCard: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: '90%',
    height: mvs(100),
    alignSelf: 'center',
    padding: mvs(6),

    // alignItems: 'center',
    elevation: 5,
    overflow: 'hidden',
    borderRadius: 5,
    marginVertical: mvs(10),
    backgroundColor: colors.white,
  },
  redLinedInnerView: {
    borderLeftWidth: mvs(6),
    borderLeftColor: '#DA0016',
    height: '100%',
    backgroundColor: '#FFE3E6',
    borderRadius: mvs(6),
    padding: mvs(7),
  },
  detailsInnerCard: {
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 2,
    // overflow: 'hidden',
    // shadowOffset: {width: -2, height: 4},
    backgroundColor: colors.white,
    borderRadius: mvs(5),
    width: '90%',
    // width: width - mvs(70),
    alignSelf: 'center',
    bottom: mvs(100),
    zIndex: 1,
    paddingHorizontal: mvs(20),
    paddingVertical: 10,
    // marginBottom: mvs(40),
    // backgroundColor: 'red',
  },
  yellowInnerLine: {
    alignSelf: 'center',
    borderWidth: 0.5,
    width: '100%',
    borderColor: colors.yellowLightLine,
    // marginVertical: 5,
  },
  imgBgHeader: {
    flexDirection: 'row',
    width: '100%',
    height: '70%',
    alignItems: 'center',
    zIndex: 200,
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    paddingHorizontal: mvs(20),

    backgroundColor: colors.white,
    // backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  tagsView: {
    backgroundColor: colors.lightLiterGrey,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: mvs(10),
    marginHorizontal: mvs(4),
    // height: mvs(22),
    // padding: 3,
    alignSelf: 'center',
    paddingVertical: mvs(4),
    paddingHorizontal: mvs(15),
    borderRadius: mvs(3),
  },
  lgBtn: {
    width: width - mvs(82),
    alignSelf: 'center',
  },
});
